comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
